version: "3.5"
services:
  hub:
    image: selenium/hub
    container_name: myHub
    ports:
      - 4444:4444
    networks:
      - my_network
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    networks:
      - my_network
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    networks:
      - my_network

networks:
  my_network:
    name: myGrid